---
location:
  city: ChangChun
  country: China
  timezone: Asia/Shanghai
  longitude: 125.35
  latitude: 43.88

# 在themes中注释后将不自动切换
# Will not switch automatically
# after commenting in themes
themes:
  - gnome
  - terminator
  - vscode
  # - vim
  - spaceVim
  - update_time

gnome:
  theme:
    # light: Mojave-light
    # light: WhiteSur-light
    light: BigSur-light
    # dark: Mojave-dark
    # dark: WhiteSur-dark
    dark: BigSur-Dark
  cursor:
    light: capitaine-cursors
    dark: capitaine-cursors-light
  shell:
    light: WhiteSur-light-solid
    dark: WhiteSur-dark-solid
  terminal:
    dark: d033acf1-5947-48b4-93cd-b8a15a9af6b6
    light: 2e87dce9-b00d-4ba2-b1ca-5a207845c298

terminator:
  path: ".config/terminator/config"
  keyword: profile
  theme:
    light: solarized light
    dark: solarized dark

vscode:
  path: ".config/Code/User/settings.json"
  key_word: workbench.colorTheme
  theme:
    # light: GitHub Light
    light: Atom One Light
    # dark: GitHub Dark
    dark: Atom One Dark

vim:
  path: ".vimrc"
  key_word: set background
  theme:
    light: light
    dark: dark

# 字符串包含特殊字符
# string include special chars
spaceVim:
  path: ".SpaceVim.d/init.toml"
  key_word: colorscheme_bg
  theme:
    light: ' "light"'
    dark: ' "dark"'
