---
location:
  city: ChangChun
  country: China
  timezone: Asia/Shanghai
  longitude: 125.35
  latitude: 43.8833

# 在themes中注释后将不自动切换
# Will not switch automatically
# after commenting in themes
themes:
  - gnome
  - vscode
  # - vim
  # - spaceVim
  - update_time

gnome:
  theme:
    light: WhiteSur-light
    night: WhiteSur-dark
  cursor:
    light: capitaine-cursors
    night: capitaine-cursors-light
  shell:
    light: WhiteSur-light
    night: WhiteSur-dark
  terminal:
    light: 658cb017-3421-4c58-88e3-08c4ef6c7c8a
    night: 6e18f627-29e8-4764-a002-efee8f2fec6f

vscode:
  path: ".config/Code/User/settings.json"
  key_word: workbench.colorTheme
  theme:
    # light: GitHub Light
    light: Atom One Light
    # night: GitHub Dark
    night: Atom One Dark

vim:
  path: ".vimrc"
  key_word: set background
  theme:
    light: light
    night: dark

# 字符串包含特殊字符
# string include special chars
spaceVim:
  path: ".SpaceVim.d/init.toml"
  key_word: colorscheme_bg
  theme:
    light: " \"light\""
    night: " \"dark\""
