---
location:
  city: ChangChun
  country: China
  timezone: Asia/Shanghai
  longitude: 125.35
  latitude: 43.88

# 在themes中注释后将不自动切换
# Will not switch automatically
# after commenting in themes
themes:
  - gnome
  - terminator
  - vscode
  # - vim
  # - spaceVim
  - update_time

gnome:
  theme:
    light: WhiteSur-light
    dark: WhiteSur-dark
  cursor:
    light: capitaine-cursors
    dark: capitaine-cursors-light
  shell:
    light: WhiteSur-light
    dark: WhiteSur-dark
  terminal:
    light: 658cb017-3421-4c58-88e3-08c4ef6c7c8a
    dark: 6e18f627-29e8-4764-a002-efee8f2fec6f

terminator:
  path: ".config/terminator/config"
  keyword: profile
  theme:
    light: solarized light
    dark: solarized dark

vscode:
  path: ".config/Code/User/settings.json"
  key_word: workbench.colorTheme
  theme:
    # light: GitHub Light
    light: Atom One Light
    # dark: GitHub Dark
    dark: Atom One Dark

vim:
  path: ".vimrc"
  key_word: set background
  theme:
    light: light
    dark: dark

# 字符串包含特殊字符
# string include special chars
spaceVim:
  path: ".SpaceVim.d/init.toml"
  key_word: colorscheme_bg
  theme:
    light: " \"light\""
    dark: " \"dark\""
