---
location:
  city: ChangChun
  country: China
  timezone: Asia/Shanghai
  longitude: 125.35
  latitude: 43.8833

# 在themes中注释后将不自动切换
# Will not switch automatically
# after commenting in themes
themes:
  - gnome
  - vscode
  # - vim
  - spaceVim
  - update_time

gnome:
  theme:
    light: Mojave-light
    night: Mojave-dark
  cursor:
    light: capitaine-cursors
    night: capitaine-cursors-light
  shell:
    light: Mojave-light
    night: Mojave-dark
  terminal:
    light: 2e064c23-220a-4ec6-9b1e-d8d0f51351de
    night: a098cf48-224b-4aee-b4ce-a02700d0b7d8

vscode:
  path: ".config/Code/User/settings.json"
  key_word: workbench.colorTheme
  theme:
    light: GitHub Light
    night: GitHub Dark

vim:
  path: ".vimrc"
  key_word: set background
  theme:
    light: light
    night: dark

# 字符串包含特殊字符
# string include special chars
spaceVim:
  path: ".SpaceVim.d/init.toml"
  key_word: colorscheme_bg
  theme:
    light: " \"light\""
    night: " \"dark\""
